---
- name: Install APT package
  hosts: all
  become: true
  vars:
    package: "curl"

  tasks:
    - name: Install package
      ansible.builtin.apt:
        name: "{{ package }}"
        update_cache: yes
        state: present
